// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package agent_protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GenericError_ErrorKind int32

const (
	GenericError_GenericError GenericError_ErrorKind = 0
	GenericError_Timeout      GenericError_ErrorKind = 1
	GenericError_Unreachable  GenericError_ErrorKind = 2
	GenericError_Cancelled    GenericError_ErrorKind = 3
	GenericError_PayloadError GenericError_ErrorKind = 4
	GenericError_AgentError   GenericError_ErrorKind = 5
)

var GenericError_ErrorKind_name = map[int32]string{
	0: "GenericError",
	1: "Timeout",
	2: "Unreachable",
	3: "Cancelled",
	4: "PayloadError",
	5: "AgentError",
}
var GenericError_ErrorKind_value = map[string]int32{
	"GenericError": 0,
	"Timeout":      1,
	"Unreachable":  2,
	"Cancelled":    3,
	"PayloadError": 4,
	"AgentError":   5,
}

func (x GenericError_ErrorKind) String() string {
	return proto.EnumName(GenericError_ErrorKind_name, int32(x))
}
func (GenericError_ErrorKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{3, 0}
}

type AgentMessage_MsgKind int32

const (
	AgentMessage_Request       AgentMessage_MsgKind = 0
	AgentMessage_Reply         AgentMessage_MsgKind = 1
	AgentMessage_Async         AgentMessage_MsgKind = 2
	AgentMessage_StreamRequest AgentMessage_MsgKind = 3
	AgentMessage_StreamReply   AgentMessage_MsgKind = 4
	AgentMessage_Error         AgentMessage_MsgKind = 5
)

var AgentMessage_MsgKind_name = map[int32]string{
	0: "Request",
	1: "Reply",
	2: "Async",
	3: "StreamRequest",
	4: "StreamReply",
	5: "Error",
}
var AgentMessage_MsgKind_value = map[string]int32{
	"Request":       0,
	"Reply":         1,
	"Async":         2,
	"StreamRequest": 3,
	"StreamReply":   4,
	"Error":         5,
}

func (x AgentMessage_MsgKind) String() string {
	return proto.EnumName(AgentMessage_MsgKind_name, int32(x))
}
func (AgentMessage_MsgKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{4, 0}
}

type IOMessage_MsgKind int32

const (
	IOMessage_stdin  IOMessage_MsgKind = 0
	IOMessage_stdout IOMessage_MsgKind = 1
	IOMessage_stderr IOMessage_MsgKind = 2
)

var IOMessage_MsgKind_name = map[int32]string{
	0: "stdin",
	1: "stdout",
	2: "stderr",
}
var IOMessage_MsgKind_value = map[string]int32{
	"stdin":  0,
	"stdout": 1,
	"stderr": 2,
}

func (x IOMessage_MsgKind) String() string {
	return proto.EnumName(IOMessage_MsgKind_name, int32(x))
}
func (IOMessage_MsgKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{16, 0}
}

type RouteMessage struct {
	Destination          int32    `protobuf:"varint,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Args                 *any.Any `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteMessage) Reset()         { *m = RouteMessage{} }
func (m *RouteMessage) String() string { return proto.CompactTextString(m) }
func (*RouteMessage) ProtoMessage()    {}
func (*RouteMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{0}
}
func (m *RouteMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteMessage.Unmarshal(m, b)
}
func (m *RouteMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteMessage.Marshal(b, m, deterministic)
}
func (dst *RouteMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteMessage.Merge(dst, src)
}
func (m *RouteMessage) XXX_Size() int {
	return xxx_messageInfo_RouteMessage.Size(m)
}
func (m *RouteMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RouteMessage proto.InternalMessageInfo

func (m *RouteMessage) GetDestination() int32 {
	if m != nil {
		return m.Destination
	}
	return 0
}

func (m *RouteMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RouteMessage) GetArgs() *any.Any {
	if m != nil {
		return m.Args
	}
	return nil
}

type McastMessage struct {
	Destinations         string   `protobuf:"bytes,1,opt,name=destinations,proto3" json:"destinations,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Args                 *any.Any `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *McastMessage) Reset()         { *m = McastMessage{} }
func (m *McastMessage) String() string { return proto.CompactTextString(m) }
func (*McastMessage) ProtoMessage()    {}
func (*McastMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{1}
}
func (m *McastMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_McastMessage.Unmarshal(m, b)
}
func (m *McastMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_McastMessage.Marshal(b, m, deterministic)
}
func (dst *McastMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_McastMessage.Merge(dst, src)
}
func (m *McastMessage) XXX_Size() int {
	return xxx_messageInfo_McastMessage.Size(m)
}
func (m *McastMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_McastMessage.DiscardUnknown(m)
}

var xxx_messageInfo_McastMessage proto.InternalMessageInfo

func (m *McastMessage) GetDestinations() string {
	if m != nil {
		return m.Destinations
	}
	return ""
}

func (m *McastMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *McastMessage) GetArgs() *any.Any {
	if m != nil {
		return m.Args
	}
	return nil
}

type RouteMessageResult struct {
	// Types that are valid to be assigned to ResultType:
	//	*RouteMessageResult_Error
	//	*RouteMessageResult_Result
	ResultType           isRouteMessageResult_ResultType `protobuf_oneof:"result_type"`
	Source               int32                           `protobuf:"varint,3,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *RouteMessageResult) Reset()         { *m = RouteMessageResult{} }
func (m *RouteMessageResult) String() string { return proto.CompactTextString(m) }
func (*RouteMessageResult) ProtoMessage()    {}
func (*RouteMessageResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{2}
}
func (m *RouteMessageResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteMessageResult.Unmarshal(m, b)
}
func (m *RouteMessageResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteMessageResult.Marshal(b, m, deterministic)
}
func (dst *RouteMessageResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteMessageResult.Merge(dst, src)
}
func (m *RouteMessageResult) XXX_Size() int {
	return xxx_messageInfo_RouteMessageResult.Size(m)
}
func (m *RouteMessageResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteMessageResult.DiscardUnknown(m)
}

var xxx_messageInfo_RouteMessageResult proto.InternalMessageInfo

type isRouteMessageResult_ResultType interface {
	isRouteMessageResult_ResultType()
}

type RouteMessageResult_Error struct {
	Error *GenericError `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type RouteMessageResult_Result struct {
	Result *any.Any `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*RouteMessageResult_Error) isRouteMessageResult_ResultType() {}

func (*RouteMessageResult_Result) isRouteMessageResult_ResultType() {}

func (m *RouteMessageResult) GetResultType() isRouteMessageResult_ResultType {
	if m != nil {
		return m.ResultType
	}
	return nil
}

func (m *RouteMessageResult) GetError() *GenericError {
	if x, ok := m.GetResultType().(*RouteMessageResult_Error); ok {
		return x.Error
	}
	return nil
}

func (m *RouteMessageResult) GetResult() *any.Any {
	if x, ok := m.GetResultType().(*RouteMessageResult_Result); ok {
		return x.Result
	}
	return nil
}

func (m *RouteMessageResult) GetSource() int32 {
	if m != nil {
		return m.Source
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RouteMessageResult) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RouteMessageResult_OneofMarshaler, _RouteMessageResult_OneofUnmarshaler, _RouteMessageResult_OneofSizer, []interface{}{
		(*RouteMessageResult_Error)(nil),
		(*RouteMessageResult_Result)(nil),
	}
}

func _RouteMessageResult_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RouteMessageResult)
	// result_type
	switch x := m.ResultType.(type) {
	case *RouteMessageResult_Error:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case *RouteMessageResult_Result:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Result); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RouteMessageResult.ResultType has unexpected type %T", x)
	}
	return nil
}

func _RouteMessageResult_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RouteMessageResult)
	switch tag {
	case 1: // result_type.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GenericError)
		err := b.DecodeMessage(msg)
		m.ResultType = &RouteMessageResult_Error{msg}
		return true, err
	case 2: // result_type.result
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(any.Any)
		err := b.DecodeMessage(msg)
		m.ResultType = &RouteMessageResult_Result{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RouteMessageResult_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RouteMessageResult)
	// result_type
	switch x := m.ResultType.(type) {
	case *RouteMessageResult_Error:
		s := proto.Size(x.Error)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RouteMessageResult_Result:
		s := proto.Size(x.Result)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GenericError struct {
	Kind                 GenericError_ErrorKind `protobuf:"varint,1,opt,name=kind,proto3,enum=GenericError_ErrorKind" json:"kind,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Details              *any.Any               `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GenericError) Reset()         { *m = GenericError{} }
func (m *GenericError) String() string { return proto.CompactTextString(m) }
func (*GenericError) ProtoMessage()    {}
func (*GenericError) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{3}
}
func (m *GenericError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericError.Unmarshal(m, b)
}
func (m *GenericError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericError.Marshal(b, m, deterministic)
}
func (dst *GenericError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericError.Merge(dst, src)
}
func (m *GenericError) XXX_Size() int {
	return xxx_messageInfo_GenericError.Size(m)
}
func (m *GenericError) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericError.DiscardUnknown(m)
}

var xxx_messageInfo_GenericError proto.InternalMessageInfo

func (m *GenericError) GetKind() GenericError_ErrorKind {
	if m != nil {
		return m.Kind
	}
	return GenericError_GenericError
}

func (m *GenericError) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GenericError) GetDetails() *any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

type AgentMessage struct {
	Kind                 AgentMessage_MsgKind `protobuf:"varint,1,opt,name=kind,proto3,enum=AgentMessage_MsgKind" json:"kind,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tag                  int64                `protobuf:"varint,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Data                 *any.Any             `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AgentMessage) Reset()         { *m = AgentMessage{} }
func (m *AgentMessage) String() string { return proto.CompactTextString(m) }
func (*AgentMessage) ProtoMessage()    {}
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{4}
}
func (m *AgentMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentMessage.Unmarshal(m, b)
}
func (m *AgentMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentMessage.Marshal(b, m, deterministic)
}
func (dst *AgentMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentMessage.Merge(dst, src)
}
func (m *AgentMessage) XXX_Size() int {
	return xxx_messageInfo_AgentMessage.Size(m)
}
func (m *AgentMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AgentMessage proto.InternalMessageInfo

func (m *AgentMessage) GetKind() AgentMessage_MsgKind {
	if m != nil {
		return m.Kind
	}
	return AgentMessage_Request
}

func (m *AgentMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AgentMessage) GetTag() int64 {
	if m != nil {
		return m.Tag
	}
	return 0
}

func (m *AgentMessage) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type ExecMessage struct {
	ExecId               int64    `protobuf:"varint,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Args                 []string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env                  []string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecMessage) Reset()         { *m = ExecMessage{} }
func (m *ExecMessage) String() string { return proto.CompactTextString(m) }
func (*ExecMessage) ProtoMessage()    {}
func (*ExecMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{5}
}
func (m *ExecMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecMessage.Unmarshal(m, b)
}
func (m *ExecMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecMessage.Marshal(b, m, deterministic)
}
func (dst *ExecMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecMessage.Merge(dst, src)
}
func (m *ExecMessage) XXX_Size() int {
	return xxx_messageInfo_ExecMessage.Size(m)
}
func (m *ExecMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ExecMessage proto.InternalMessageInfo

func (m *ExecMessage) GetExecId() int64 {
	if m != nil {
		return m.ExecId
	}
	return 0
}

func (m *ExecMessage) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *ExecMessage) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *ExecMessage) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *ExecMessage) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type ExecResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecResult) Reset()         { *m = ExecResult{} }
func (m *ExecResult) String() string { return proto.CompactTextString(m) }
func (*ExecResult) ProtoMessage()    {}
func (*ExecResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{6}
}
func (m *ExecResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecResult.Unmarshal(m, b)
}
func (m *ExecResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecResult.Marshal(b, m, deterministic)
}
func (dst *ExecResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecResult.Merge(dst, src)
}
func (m *ExecResult) XXX_Size() int {
	return xxx_messageInfo_ExecResult.Size(m)
}
func (m *ExecResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecResult.DiscardUnknown(m)
}

var xxx_messageInfo_ExecResult proto.InternalMessageInfo

type ListExecMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListExecMessage) Reset()         { *m = ListExecMessage{} }
func (m *ListExecMessage) String() string { return proto.CompactTextString(m) }
func (*ListExecMessage) ProtoMessage()    {}
func (*ListExecMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{7}
}
func (m *ListExecMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListExecMessage.Unmarshal(m, b)
}
func (m *ListExecMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListExecMessage.Marshal(b, m, deterministic)
}
func (dst *ListExecMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListExecMessage.Merge(dst, src)
}
func (m *ListExecMessage) XXX_Size() int {
	return xxx_messageInfo_ListExecMessage.Size(m)
}
func (m *ListExecMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ListExecMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ListExecMessage proto.InternalMessageInfo

type ExecInfo struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Attached             bool     `protobuf:"varint,2,opt,name=attached,proto3" json:"attached,omitempty"`
	Running              bool     `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecInfo) Reset()         { *m = ExecInfo{} }
func (m *ExecInfo) String() string { return proto.CompactTextString(m) }
func (*ExecInfo) ProtoMessage()    {}
func (*ExecInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{8}
}
func (m *ExecInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecInfo.Unmarshal(m, b)
}
func (m *ExecInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecInfo.Marshal(b, m, deterministic)
}
func (dst *ExecInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecInfo.Merge(dst, src)
}
func (m *ExecInfo) XXX_Size() int {
	return xxx_messageInfo_ExecInfo.Size(m)
}
func (m *ExecInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ExecInfo proto.InternalMessageInfo

func (m *ExecInfo) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *ExecInfo) GetAttached() bool {
	if m != nil {
		return m.Attached
	}
	return false
}

func (m *ExecInfo) GetRunning() bool {
	if m != nil {
		return m.Running
	}
	return false
}

type ListExecResult struct {
	Execs                map[int64]*ExecInfo `protobuf:"bytes,1,rep,name=execs,proto3" json:"execs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListExecResult) Reset()         { *m = ListExecResult{} }
func (m *ListExecResult) String() string { return proto.CompactTextString(m) }
func (*ListExecResult) ProtoMessage()    {}
func (*ListExecResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{9}
}
func (m *ListExecResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListExecResult.Unmarshal(m, b)
}
func (m *ListExecResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListExecResult.Marshal(b, m, deterministic)
}
func (dst *ListExecResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListExecResult.Merge(dst, src)
}
func (m *ListExecResult) XXX_Size() int {
	return xxx_messageInfo_ListExecResult.Size(m)
}
func (m *ListExecResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ListExecResult.DiscardUnknown(m)
}

var xxx_messageInfo_ListExecResult proto.InternalMessageInfo

func (m *ListExecResult) GetExecs() map[int64]*ExecInfo {
	if m != nil {
		return m.Execs
	}
	return nil
}

type AttachMessage struct {
	ExecId               int64    `protobuf:"varint,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachMessage) Reset()         { *m = AttachMessage{} }
func (m *AttachMessage) String() string { return proto.CompactTextString(m) }
func (*AttachMessage) ProtoMessage()    {}
func (*AttachMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{10}
}
func (m *AttachMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachMessage.Unmarshal(m, b)
}
func (m *AttachMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachMessage.Marshal(b, m, deterministic)
}
func (dst *AttachMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachMessage.Merge(dst, src)
}
func (m *AttachMessage) XXX_Size() int {
	return xxx_messageInfo_AttachMessage.Size(m)
}
func (m *AttachMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AttachMessage proto.InternalMessageInfo

func (m *AttachMessage) GetExecId() int64 {
	if m != nil {
		return m.ExecId
	}
	return 0
}

type AttachResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachResult) Reset()         { *m = AttachResult{} }
func (m *AttachResult) String() string { return proto.CompactTextString(m) }
func (*AttachResult) ProtoMessage()    {}
func (*AttachResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{11}
}
func (m *AttachResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachResult.Unmarshal(m, b)
}
func (m *AttachResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachResult.Marshal(b, m, deterministic)
}
func (dst *AttachResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachResult.Merge(dst, src)
}
func (m *AttachResult) XXX_Size() int {
	return xxx_messageInfo_AttachResult.Size(m)
}
func (m *AttachResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachResult.DiscardUnknown(m)
}

var xxx_messageInfo_AttachResult proto.InternalMessageInfo

type DetachMessage struct {
	ExecId               int64    `protobuf:"varint,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Tag                  int64    `protobuf:"varint,3,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetachMessage) Reset()         { *m = DetachMessage{} }
func (m *DetachMessage) String() string { return proto.CompactTextString(m) }
func (*DetachMessage) ProtoMessage()    {}
func (*DetachMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{12}
}
func (m *DetachMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetachMessage.Unmarshal(m, b)
}
func (m *DetachMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetachMessage.Marshal(b, m, deterministic)
}
func (dst *DetachMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetachMessage.Merge(dst, src)
}
func (m *DetachMessage) XXX_Size() int {
	return xxx_messageInfo_DetachMessage.Size(m)
}
func (m *DetachMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DetachMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DetachMessage proto.InternalMessageInfo

func (m *DetachMessage) GetExecId() int64 {
	if m != nil {
		return m.ExecId
	}
	return 0
}

func (m *DetachMessage) GetTag() int64 {
	if m != nil {
		return m.Tag
	}
	return 0
}

type DetachResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetachResult) Reset()         { *m = DetachResult{} }
func (m *DetachResult) String() string { return proto.CompactTextString(m) }
func (*DetachResult) ProtoMessage()    {}
func (*DetachResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{13}
}
func (m *DetachResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetachResult.Unmarshal(m, b)
}
func (m *DetachResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetachResult.Marshal(b, m, deterministic)
}
func (dst *DetachResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetachResult.Merge(dst, src)
}
func (m *DetachResult) XXX_Size() int {
	return xxx_messageInfo_DetachResult.Size(m)
}
func (m *DetachResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DetachResult.DiscardUnknown(m)
}

var xxx_messageInfo_DetachResult proto.InternalMessageInfo

type KillMessage struct {
	ExecId               int64    `protobuf:"varint,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillMessage) Reset()         { *m = KillMessage{} }
func (m *KillMessage) String() string { return proto.CompactTextString(m) }
func (*KillMessage) ProtoMessage()    {}
func (*KillMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{14}
}
func (m *KillMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillMessage.Unmarshal(m, b)
}
func (m *KillMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillMessage.Marshal(b, m, deterministic)
}
func (dst *KillMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillMessage.Merge(dst, src)
}
func (m *KillMessage) XXX_Size() int {
	return xxx_messageInfo_KillMessage.Size(m)
}
func (m *KillMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_KillMessage.DiscardUnknown(m)
}

var xxx_messageInfo_KillMessage proto.InternalMessageInfo

func (m *KillMessage) GetExecId() int64 {
	if m != nil {
		return m.ExecId
	}
	return 0
}

type KillResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillResult) Reset()         { *m = KillResult{} }
func (m *KillResult) String() string { return proto.CompactTextString(m) }
func (*KillResult) ProtoMessage()    {}
func (*KillResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{15}
}
func (m *KillResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillResult.Unmarshal(m, b)
}
func (m *KillResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillResult.Marshal(b, m, deterministic)
}
func (dst *KillResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillResult.Merge(dst, src)
}
func (m *KillResult) XXX_Size() int {
	return xxx_messageInfo_KillResult.Size(m)
}
func (m *KillResult) XXX_DiscardUnknown() {
	xxx_messageInfo_KillResult.DiscardUnknown(m)
}

var xxx_messageInfo_KillResult proto.InternalMessageInfo

type IOMessage struct {
	Kind                 IOMessage_MsgKind `protobuf:"varint,1,opt,name=kind,proto3,enum=IOMessage_MsgKind" json:"kind,omitempty"`
	Eof                  bool              `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
	Data                 []byte            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ExecId               int64             `protobuf:"varint,4,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *IOMessage) Reset()         { *m = IOMessage{} }
func (m *IOMessage) String() string { return proto.CompactTextString(m) }
func (*IOMessage) ProtoMessage()    {}
func (*IOMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{16}
}
func (m *IOMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IOMessage.Unmarshal(m, b)
}
func (m *IOMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IOMessage.Marshal(b, m, deterministic)
}
func (dst *IOMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IOMessage.Merge(dst, src)
}
func (m *IOMessage) XXX_Size() int {
	return xxx_messageInfo_IOMessage.Size(m)
}
func (m *IOMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_IOMessage.DiscardUnknown(m)
}

var xxx_messageInfo_IOMessage proto.InternalMessageInfo

func (m *IOMessage) GetKind() IOMessage_MsgKind {
	if m != nil {
		return m.Kind
	}
	return IOMessage_stdin
}

func (m *IOMessage) GetEof() bool {
	if m != nil {
		return m.Eof
	}
	return false
}

func (m *IOMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *IOMessage) GetExecId() int64 {
	if m != nil {
		return m.ExecId
	}
	return 0
}

type IOResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IOResult) Reset()         { *m = IOResult{} }
func (m *IOResult) String() string { return proto.CompactTextString(m) }
func (*IOResult) ProtoMessage()    {}
func (*IOResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{17}
}
func (m *IOResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IOResult.Unmarshal(m, b)
}
func (m *IOResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IOResult.Marshal(b, m, deterministic)
}
func (dst *IOResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IOResult.Merge(dst, src)
}
func (m *IOResult) XXX_Size() int {
	return xxx_messageInfo_IOResult.Size(m)
}
func (m *IOResult) XXX_DiscardUnknown() {
	xxx_messageInfo_IOResult.DiscardUnknown(m)
}

var xxx_messageInfo_IOResult proto.InternalMessageInfo

type ExitStatus struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExitStatus) Reset()         { *m = ExitStatus{} }
func (m *ExitStatus) String() string { return proto.CompactTextString(m) }
func (*ExitStatus) ProtoMessage()    {}
func (*ExitStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{18}
}
func (m *ExitStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitStatus.Unmarshal(m, b)
}
func (m *ExitStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitStatus.Marshal(b, m, deterministic)
}
func (dst *ExitStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitStatus.Merge(dst, src)
}
func (m *ExitStatus) XXX_Size() int {
	return xxx_messageInfo_ExitStatus.Size(m)
}
func (m *ExitStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ExitStatus proto.InternalMessageInfo

func (m *ExitStatus) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ThawMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThawMessage) Reset()         { *m = ThawMessage{} }
func (m *ThawMessage) String() string { return proto.CompactTextString(m) }
func (*ThawMessage) ProtoMessage()    {}
func (*ThawMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{19}
}
func (m *ThawMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThawMessage.Unmarshal(m, b)
}
func (m *ThawMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThawMessage.Marshal(b, m, deterministic)
}
func (dst *ThawMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThawMessage.Merge(dst, src)
}
func (m *ThawMessage) XXX_Size() int {
	return xxx_messageInfo_ThawMessage.Size(m)
}
func (m *ThawMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ThawMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ThawMessage proto.InternalMessageInfo

type ThawResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThawResult) Reset()         { *m = ThawResult{} }
func (m *ThawResult) String() string { return proto.CompactTextString(m) }
func (*ThawResult) ProtoMessage()    {}
func (*ThawResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{20}
}
func (m *ThawResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThawResult.Unmarshal(m, b)
}
func (m *ThawResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThawResult.Marshal(b, m, deterministic)
}
func (dst *ThawResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThawResult.Merge(dst, src)
}
func (m *ThawResult) XXX_Size() int {
	return xxx_messageInfo_ThawResult.Size(m)
}
func (m *ThawResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ThawResult.DiscardUnknown(m)
}

var xxx_messageInfo_ThawResult proto.InternalMessageInfo

type FreezeMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FreezeMessage) Reset()         { *m = FreezeMessage{} }
func (m *FreezeMessage) String() string { return proto.CompactTextString(m) }
func (*FreezeMessage) ProtoMessage()    {}
func (*FreezeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{21}
}
func (m *FreezeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FreezeMessage.Unmarshal(m, b)
}
func (m *FreezeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FreezeMessage.Marshal(b, m, deterministic)
}
func (dst *FreezeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FreezeMessage.Merge(dst, src)
}
func (m *FreezeMessage) XXX_Size() int {
	return xxx_messageInfo_FreezeMessage.Size(m)
}
func (m *FreezeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FreezeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FreezeMessage proto.InternalMessageInfo

type FreezeResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FreezeResult) Reset()         { *m = FreezeResult{} }
func (m *FreezeResult) String() string { return proto.CompactTextString(m) }
func (*FreezeResult) ProtoMessage()    {}
func (*FreezeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{22}
}
func (m *FreezeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FreezeResult.Unmarshal(m, b)
}
func (m *FreezeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FreezeResult.Marshal(b, m, deterministic)
}
func (dst *FreezeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FreezeResult.Merge(dst, src)
}
func (m *FreezeResult) XXX_Size() int {
	return xxx_messageInfo_FreezeResult.Size(m)
}
func (m *FreezeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FreezeResult.DiscardUnknown(m)
}

var xxx_messageInfo_FreezeResult proto.InternalMessageInfo

type HelloMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloMessage) Reset()         { *m = HelloMessage{} }
func (m *HelloMessage) String() string { return proto.CompactTextString(m) }
func (*HelloMessage) ProtoMessage()    {}
func (*HelloMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{23}
}
func (m *HelloMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloMessage.Unmarshal(m, b)
}
func (m *HelloMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloMessage.Marshal(b, m, deterministic)
}
func (dst *HelloMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloMessage.Merge(dst, src)
}
func (m *HelloMessage) XXX_Size() int {
	return xxx_messageInfo_HelloMessage.Size(m)
}
func (m *HelloMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HelloMessage proto.InternalMessageInfo

type HelloResult struct {
	Epoch                int64    `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResult) Reset()         { *m = HelloResult{} }
func (m *HelloResult) String() string { return proto.CompactTextString(m) }
func (*HelloResult) ProtoMessage()    {}
func (*HelloResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{24}
}
func (m *HelloResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResult.Unmarshal(m, b)
}
func (m *HelloResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResult.Marshal(b, m, deterministic)
}
func (dst *HelloResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResult.Merge(dst, src)
}
func (m *HelloResult) XXX_Size() int {
	return xxx_messageInfo_HelloResult.Size(m)
}
func (m *HelloResult) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResult.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResult proto.InternalMessageInfo

func (m *HelloResult) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *HelloResult) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type MkdirMessage struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode                 uint32   `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	MakeParent           bool     `protobuf:"varint,3,opt,name=make_parent,json=makeParent,proto3" json:"make_parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MkdirMessage) Reset()         { *m = MkdirMessage{} }
func (m *MkdirMessage) String() string { return proto.CompactTextString(m) }
func (*MkdirMessage) ProtoMessage()    {}
func (*MkdirMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{25}
}
func (m *MkdirMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MkdirMessage.Unmarshal(m, b)
}
func (m *MkdirMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MkdirMessage.Marshal(b, m, deterministic)
}
func (dst *MkdirMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MkdirMessage.Merge(dst, src)
}
func (m *MkdirMessage) XXX_Size() int {
	return xxx_messageInfo_MkdirMessage.Size(m)
}
func (m *MkdirMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MkdirMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MkdirMessage proto.InternalMessageInfo

func (m *MkdirMessage) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *MkdirMessage) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *MkdirMessage) GetMakeParent() bool {
	if m != nil {
		return m.MakeParent
	}
	return false
}

type MkdirResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MkdirResult) Reset()         { *m = MkdirResult{} }
func (m *MkdirResult) String() string { return proto.CompactTextString(m) }
func (*MkdirResult) ProtoMessage()    {}
func (*MkdirResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{26}
}
func (m *MkdirResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MkdirResult.Unmarshal(m, b)
}
func (m *MkdirResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MkdirResult.Marshal(b, m, deterministic)
}
func (dst *MkdirResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MkdirResult.Merge(dst, src)
}
func (m *MkdirResult) XXX_Size() int {
	return xxx_messageInfo_MkdirResult.Size(m)
}
func (m *MkdirResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MkdirResult.DiscardUnknown(m)
}

var xxx_messageInfo_MkdirResult proto.InternalMessageInfo

type HostnameMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostnameMessage) Reset()         { *m = HostnameMessage{} }
func (m *HostnameMessage) String() string { return proto.CompactTextString(m) }
func (*HostnameMessage) ProtoMessage()    {}
func (*HostnameMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{27}
}
func (m *HostnameMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostnameMessage.Unmarshal(m, b)
}
func (m *HostnameMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostnameMessage.Marshal(b, m, deterministic)
}
func (dst *HostnameMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostnameMessage.Merge(dst, src)
}
func (m *HostnameMessage) XXX_Size() int {
	return xxx_messageInfo_HostnameMessage.Size(m)
}
func (m *HostnameMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HostnameMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HostnameMessage proto.InternalMessageInfo

type HostnameResult struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostnameResult) Reset()         { *m = HostnameResult{} }
func (m *HostnameResult) String() string { return proto.CompactTextString(m) }
func (*HostnameResult) ProtoMessage()    {}
func (*HostnameResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{28}
}
func (m *HostnameResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostnameResult.Unmarshal(m, b)
}
func (m *HostnameResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostnameResult.Marshal(b, m, deterministic)
}
func (dst *HostnameResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostnameResult.Merge(dst, src)
}
func (m *HostnameResult) XXX_Size() int {
	return xxx_messageInfo_HostnameResult.Size(m)
}
func (m *HostnameResult) XXX_DiscardUnknown() {
	xxx_messageInfo_HostnameResult.DiscardUnknown(m)
}

var xxx_messageInfo_HostnameResult proto.InternalMessageInfo

func (m *HostnameResult) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type ChmodMessage struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode                 uint32   `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Recurse              bool     `protobuf:"varint,3,opt,name=recurse,proto3" json:"recurse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChmodMessage) Reset()         { *m = ChmodMessage{} }
func (m *ChmodMessage) String() string { return proto.CompactTextString(m) }
func (*ChmodMessage) ProtoMessage()    {}
func (*ChmodMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{29}
}
func (m *ChmodMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChmodMessage.Unmarshal(m, b)
}
func (m *ChmodMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChmodMessage.Marshal(b, m, deterministic)
}
func (dst *ChmodMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChmodMessage.Merge(dst, src)
}
func (m *ChmodMessage) XXX_Size() int {
	return xxx_messageInfo_ChmodMessage.Size(m)
}
func (m *ChmodMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChmodMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChmodMessage proto.InternalMessageInfo

func (m *ChmodMessage) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ChmodMessage) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *ChmodMessage) GetRecurse() bool {
	if m != nil {
		return m.Recurse
	}
	return false
}

type ChmodResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChmodResult) Reset()         { *m = ChmodResult{} }
func (m *ChmodResult) String() string { return proto.CompactTextString(m) }
func (*ChmodResult) ProtoMessage()    {}
func (*ChmodResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{30}
}
func (m *ChmodResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChmodResult.Unmarshal(m, b)
}
func (m *ChmodResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChmodResult.Marshal(b, m, deterministic)
}
func (dst *ChmodResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChmodResult.Merge(dst, src)
}
func (m *ChmodResult) XXX_Size() int {
	return xxx_messageInfo_ChmodResult.Size(m)
}
func (m *ChmodResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ChmodResult.DiscardUnknown(m)
}

var xxx_messageInfo_ChmodResult proto.InternalMessageInfo

type ChownMessage struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Uid                  uint32   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint32   `protobuf:"varint,3,opt,name=gid,proto3" json:"gid,omitempty"`
	Recurse              bool     `protobuf:"varint,4,opt,name=recurse,proto3" json:"recurse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChownMessage) Reset()         { *m = ChownMessage{} }
func (m *ChownMessage) String() string { return proto.CompactTextString(m) }
func (*ChownMessage) ProtoMessage()    {}
func (*ChownMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{31}
}
func (m *ChownMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChownMessage.Unmarshal(m, b)
}
func (m *ChownMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChownMessage.Marshal(b, m, deterministic)
}
func (dst *ChownMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChownMessage.Merge(dst, src)
}
func (m *ChownMessage) XXX_Size() int {
	return xxx_messageInfo_ChownMessage.Size(m)
}
func (m *ChownMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChownMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChownMessage proto.InternalMessageInfo

func (m *ChownMessage) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ChownMessage) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ChownMessage) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *ChownMessage) GetRecurse() bool {
	if m != nil {
		return m.Recurse
	}
	return false
}

type ChownResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChownResult) Reset()         { *m = ChownResult{} }
func (m *ChownResult) String() string { return proto.CompactTextString(m) }
func (*ChownResult) ProtoMessage()    {}
func (*ChownResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{32}
}
func (m *ChownResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChownResult.Unmarshal(m, b)
}
func (m *ChownResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChownResult.Marshal(b, m, deterministic)
}
func (dst *ChownResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChownResult.Merge(dst, src)
}
func (m *ChownResult) XXX_Size() int {
	return xxx_messageInfo_ChownResult.Size(m)
}
func (m *ChownResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ChownResult.DiscardUnknown(m)
}

var xxx_messageInfo_ChownResult proto.InternalMessageInfo

type SymlinkMessage struct {
	Src                  string   `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst                  string   `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SymlinkMessage) Reset()         { *m = SymlinkMessage{} }
func (m *SymlinkMessage) String() string { return proto.CompactTextString(m) }
func (*SymlinkMessage) ProtoMessage()    {}
func (*SymlinkMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{33}
}
func (m *SymlinkMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SymlinkMessage.Unmarshal(m, b)
}
func (m *SymlinkMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SymlinkMessage.Marshal(b, m, deterministic)
}
func (dst *SymlinkMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SymlinkMessage.Merge(dst, src)
}
func (m *SymlinkMessage) XXX_Size() int {
	return xxx_messageInfo_SymlinkMessage.Size(m)
}
func (m *SymlinkMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SymlinkMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SymlinkMessage proto.InternalMessageInfo

func (m *SymlinkMessage) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *SymlinkMessage) GetDst() string {
	if m != nil {
		return m.Dst
	}
	return ""
}

type SymlinkResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SymlinkResult) Reset()         { *m = SymlinkResult{} }
func (m *SymlinkResult) String() string { return proto.CompactTextString(m) }
func (*SymlinkResult) ProtoMessage()    {}
func (*SymlinkResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{34}
}
func (m *SymlinkResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SymlinkResult.Unmarshal(m, b)
}
func (m *SymlinkResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SymlinkResult.Marshal(b, m, deterministic)
}
func (dst *SymlinkResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SymlinkResult.Merge(dst, src)
}
func (m *SymlinkResult) XXX_Size() int {
	return xxx_messageInfo_SymlinkResult.Size(m)
}
func (m *SymlinkResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SymlinkResult.DiscardUnknown(m)
}

var xxx_messageInfo_SymlinkResult proto.InternalMessageInfo

type RemoveMessage struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recurse              bool     `protobuf:"varint,2,opt,name=recurse,proto3" json:"recurse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveMessage) Reset()         { *m = RemoveMessage{} }
func (m *RemoveMessage) String() string { return proto.CompactTextString(m) }
func (*RemoveMessage) ProtoMessage()    {}
func (*RemoveMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{35}
}
func (m *RemoveMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveMessage.Unmarshal(m, b)
}
func (m *RemoveMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveMessage.Marshal(b, m, deterministic)
}
func (dst *RemoveMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveMessage.Merge(dst, src)
}
func (m *RemoveMessage) XXX_Size() int {
	return xxx_messageInfo_RemoveMessage.Size(m)
}
func (m *RemoveMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveMessage proto.InternalMessageInfo

func (m *RemoveMessage) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RemoveMessage) GetRecurse() bool {
	if m != nil {
		return m.Recurse
	}
	return false
}

type RemoveResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveResult) Reset()         { *m = RemoveResult{} }
func (m *RemoveResult) String() string { return proto.CompactTextString(m) }
func (*RemoveResult) ProtoMessage()    {}
func (*RemoveResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{36}
}
func (m *RemoveResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveResult.Unmarshal(m, b)
}
func (m *RemoveResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveResult.Marshal(b, m, deterministic)
}
func (dst *RemoveResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveResult.Merge(dst, src)
}
func (m *RemoveResult) XXX_Size() int {
	return xxx_messageInfo_RemoveResult.Size(m)
}
func (m *RemoveResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveResult.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveResult proto.InternalMessageInfo

type MoveMessage struct {
	Src                  string   `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst                  string   `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveMessage) Reset()         { *m = MoveMessage{} }
func (m *MoveMessage) String() string { return proto.CompactTextString(m) }
func (*MoveMessage) ProtoMessage()    {}
func (*MoveMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{37}
}
func (m *MoveMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveMessage.Unmarshal(m, b)
}
func (m *MoveMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveMessage.Marshal(b, m, deterministic)
}
func (dst *MoveMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveMessage.Merge(dst, src)
}
func (m *MoveMessage) XXX_Size() int {
	return xxx_messageInfo_MoveMessage.Size(m)
}
func (m *MoveMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MoveMessage proto.InternalMessageInfo

func (m *MoveMessage) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *MoveMessage) GetDst() string {
	if m != nil {
		return m.Dst
	}
	return ""
}

type MoveResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveResult) Reset()         { *m = MoveResult{} }
func (m *MoveResult) String() string { return proto.CompactTextString(m) }
func (*MoveResult) ProtoMessage()    {}
func (*MoveResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{38}
}
func (m *MoveResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResult.Unmarshal(m, b)
}
func (m *MoveResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResult.Marshal(b, m, deterministic)
}
func (dst *MoveResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResult.Merge(dst, src)
}
func (m *MoveResult) XXX_Size() int {
	return xxx_messageInfo_MoveResult.Size(m)
}
func (m *MoveResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResult.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResult proto.InternalMessageInfo

type TruncateMessage struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TruncateMessage) Reset()         { *m = TruncateMessage{} }
func (m *TruncateMessage) String() string { return proto.CompactTextString(m) }
func (*TruncateMessage) ProtoMessage()    {}
func (*TruncateMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{39}
}
func (m *TruncateMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TruncateMessage.Unmarshal(m, b)
}
func (m *TruncateMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TruncateMessage.Marshal(b, m, deterministic)
}
func (dst *TruncateMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TruncateMessage.Merge(dst, src)
}
func (m *TruncateMessage) XXX_Size() int {
	return xxx_messageInfo_TruncateMessage.Size(m)
}
func (m *TruncateMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TruncateMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TruncateMessage proto.InternalMessageInfo

func (m *TruncateMessage) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *TruncateMessage) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type TruncateResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TruncateResult) Reset()         { *m = TruncateResult{} }
func (m *TruncateResult) String() string { return proto.CompactTextString(m) }
func (*TruncateResult) ProtoMessage()    {}
func (*TruncateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{40}
}
func (m *TruncateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TruncateResult.Unmarshal(m, b)
}
func (m *TruncateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TruncateResult.Marshal(b, m, deterministic)
}
func (dst *TruncateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TruncateResult.Merge(dst, src)
}
func (m *TruncateResult) XXX_Size() int {
	return xxx_messageInfo_TruncateResult.Size(m)
}
func (m *TruncateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TruncateResult.DiscardUnknown(m)
}

var xxx_messageInfo_TruncateResult proto.InternalMessageInfo

type StatMessage struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatMessage) Reset()         { *m = StatMessage{} }
func (m *StatMessage) String() string { return proto.CompactTextString(m) }
func (*StatMessage) ProtoMessage()    {}
func (*StatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{41}
}
func (m *StatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatMessage.Unmarshal(m, b)
}
func (m *StatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatMessage.Marshal(b, m, deterministic)
}
func (dst *StatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatMessage.Merge(dst, src)
}
func (m *StatMessage) XXX_Size() int {
	return xxx_messageInfo_StatMessage.Size(m)
}
func (m *StatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StatMessage proto.InternalMessageInfo

func (m *StatMessage) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type StatResult struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64                `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode                 int32                `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTime              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	IsDir                bool                 `protobuf:"varint,5,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StatResult) Reset()         { *m = StatResult{} }
func (m *StatResult) String() string { return proto.CompactTextString(m) }
func (*StatResult) ProtoMessage()    {}
func (*StatResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{42}
}
func (m *StatResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatResult.Unmarshal(m, b)
}
func (m *StatResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatResult.Marshal(b, m, deterministic)
}
func (dst *StatResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatResult.Merge(dst, src)
}
func (m *StatResult) XXX_Size() int {
	return xxx_messageInfo_StatResult.Size(m)
}
func (m *StatResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StatResult.DiscardUnknown(m)
}

var xxx_messageInfo_StatResult proto.InternalMessageInfo

func (m *StatResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StatResult) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StatResult) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *StatResult) GetModTime() *timestamp.Timestamp {
	if m != nil {
		return m.ModTime
	}
	return nil
}

func (m *StatResult) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

type WriteFileMessage struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Perms                int32    `protobuf:"varint,4,opt,name=perms,proto3" json:"perms,omitempty"`
	Append               bool     `protobuf:"varint,3,opt,name=append,proto3" json:"append,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteFileMessage) Reset()         { *m = WriteFileMessage{} }
func (m *WriteFileMessage) String() string { return proto.CompactTextString(m) }
func (*WriteFileMessage) ProtoMessage()    {}
func (*WriteFileMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{43}
}
func (m *WriteFileMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteFileMessage.Unmarshal(m, b)
}
func (m *WriteFileMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteFileMessage.Marshal(b, m, deterministic)
}
func (dst *WriteFileMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteFileMessage.Merge(dst, src)
}
func (m *WriteFileMessage) XXX_Size() int {
	return xxx_messageInfo_WriteFileMessage.Size(m)
}
func (m *WriteFileMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteFileMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WriteFileMessage proto.InternalMessageInfo

func (m *WriteFileMessage) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *WriteFileMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *WriteFileMessage) GetPerms() int32 {
	if m != nil {
		return m.Perms
	}
	return 0
}

func (m *WriteFileMessage) GetAppend() bool {
	if m != nil {
		return m.Append
	}
	return false
}

type WriteFileResult struct {
	Written              int64    `protobuf:"varint,1,opt,name=written,proto3" json:"written,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteFileResult) Reset()         { *m = WriteFileResult{} }
func (m *WriteFileResult) String() string { return proto.CompactTextString(m) }
func (*WriteFileResult) ProtoMessage()    {}
func (*WriteFileResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_0dfaf1e1a56f75b3, []int{44}
}
func (m *WriteFileResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteFileResult.Unmarshal(m, b)
}
func (m *WriteFileResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteFileResult.Marshal(b, m, deterministic)
}
func (dst *WriteFileResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteFileResult.Merge(dst, src)
}
func (m *WriteFileResult) XXX_Size() int {
	return xxx_messageInfo_WriteFileResult.Size(m)
}
func (m *WriteFileResult) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteFileResult.DiscardUnknown(m)
}

var xxx_messageInfo_WriteFileResult proto.InternalMessageInfo

func (m *WriteFileResult) GetWritten() int64 {
	if m != nil {
		return m.Written
	}
	return 0
}

func init() {
	proto.RegisterType((*RouteMessage)(nil), "RouteMessage")
	proto.RegisterType((*McastMessage)(nil), "McastMessage")
	proto.RegisterType((*RouteMessageResult)(nil), "RouteMessageResult")
	proto.RegisterType((*GenericError)(nil), "GenericError")
	proto.RegisterType((*AgentMessage)(nil), "AgentMessage")
	proto.RegisterType((*ExecMessage)(nil), "ExecMessage")
	proto.RegisterType((*ExecResult)(nil), "ExecResult")
	proto.RegisterType((*ListExecMessage)(nil), "ListExecMessage")
	proto.RegisterType((*ExecInfo)(nil), "ExecInfo")
	proto.RegisterType((*ListExecResult)(nil), "ListExecResult")
	proto.RegisterMapType((map[int64]*ExecInfo)(nil), "ListExecResult.ExecsEntry")
	proto.RegisterType((*AttachMessage)(nil), "AttachMessage")
	proto.RegisterType((*AttachResult)(nil), "AttachResult")
	proto.RegisterType((*DetachMessage)(nil), "DetachMessage")
	proto.RegisterType((*DetachResult)(nil), "DetachResult")
	proto.RegisterType((*KillMessage)(nil), "KillMessage")
	proto.RegisterType((*KillResult)(nil), "KillResult")
	proto.RegisterType((*IOMessage)(nil), "IOMessage")
	proto.RegisterType((*IOResult)(nil), "IOResult")
	proto.RegisterType((*ExitStatus)(nil), "ExitStatus")
	proto.RegisterType((*ThawMessage)(nil), "ThawMessage")
	proto.RegisterType((*ThawResult)(nil), "ThawResult")
	proto.RegisterType((*FreezeMessage)(nil), "FreezeMessage")
	proto.RegisterType((*FreezeResult)(nil), "FreezeResult")
	proto.RegisterType((*HelloMessage)(nil), "HelloMessage")
	proto.RegisterType((*HelloResult)(nil), "HelloResult")
	proto.RegisterType((*MkdirMessage)(nil), "MkdirMessage")
	proto.RegisterType((*MkdirResult)(nil), "MkdirResult")
	proto.RegisterType((*HostnameMessage)(nil), "HostnameMessage")
	proto.RegisterType((*HostnameResult)(nil), "HostnameResult")
	proto.RegisterType((*ChmodMessage)(nil), "ChmodMessage")
	proto.RegisterType((*ChmodResult)(nil), "ChmodResult")
	proto.RegisterType((*ChownMessage)(nil), "ChownMessage")
	proto.RegisterType((*ChownResult)(nil), "ChownResult")
	proto.RegisterType((*SymlinkMessage)(nil), "SymlinkMessage")
	proto.RegisterType((*SymlinkResult)(nil), "SymlinkResult")
	proto.RegisterType((*RemoveMessage)(nil), "RemoveMessage")
	proto.RegisterType((*RemoveResult)(nil), "RemoveResult")
	proto.RegisterType((*MoveMessage)(nil), "MoveMessage")
	proto.RegisterType((*MoveResult)(nil), "MoveResult")
	proto.RegisterType((*TruncateMessage)(nil), "TruncateMessage")
	proto.RegisterType((*TruncateResult)(nil), "TruncateResult")
	proto.RegisterType((*StatMessage)(nil), "StatMessage")
	proto.RegisterType((*StatResult)(nil), "StatResult")
	proto.RegisterType((*WriteFileMessage)(nil), "WriteFileMessage")
	proto.RegisterType((*WriteFileResult)(nil), "WriteFileResult")
	proto.RegisterEnum("GenericError_ErrorKind", GenericError_ErrorKind_name, GenericError_ErrorKind_value)
	proto.RegisterEnum("AgentMessage_MsgKind", AgentMessage_MsgKind_name, AgentMessage_MsgKind_value)
	proto.RegisterEnum("IOMessage_MsgKind", IOMessage_MsgKind_name, IOMessage_MsgKind_value)
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_agent_0dfaf1e1a56f75b3) }

var fileDescriptor_agent_0dfaf1e1a56f75b3 = []byte{
	// 1273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x4d, 0x6f, 0xdb, 0x46,
	0x13, 0x36, 0x25, 0xd1, 0x92, 0x86, 0xa4, 0xcc, 0xf0, 0x4d, 0xde, 0xa8, 0xba, 0xc4, 0x25, 0xda,
	0x40, 0x45, 0x02, 0x26, 0x75, 0xda, 0xa2, 0x0d, 0x90, 0x83, 0xf3, 0x55, 0x1b, 0xa9, 0x9b, 0x80,
	0x71, 0x11, 0xa0, 0x2d, 0xa0, 0x6e, 0xc8, 0xb5, 0x44, 0x98, 0x5c, 0xaa, 0xbb, 0x2b, 0x3b, 0xca,
	0xb9, 0x40, 0xef, 0x3d, 0xf4, 0xdc, 0x5f, 0xd7, 0x3f, 0xd1, 0x4b, 0x31, 0xfb, 0xa1, 0x50, 0x89,
	0x6b, 0xa7, 0xe8, 0x85, 0x98, 0x19, 0xce, 0xc7, 0x33, 0xbb, 0xcf, 0xec, 0x2e, 0x78, 0x64, 0x4a,
	0x99, 0x4c, 0xe6, 0xbc, 0x96, 0xf5, 0xe8, 0x83, 0x69, 0x5d, 0x4f, 0x4b, 0x7a, 0x4b, 0x69, 0x2f,
	0x17, 0x47, 0xb7, 0x08, 0x5b, 0x9a, 0x5f, 0xd7, 0xde, 0xfe, 0x25, 0x8b, 0x8a, 0x0a, 0x49, 0xaa,
	0xb9, 0x76, 0x88, 0x19, 0xf8, 0x69, 0xbd, 0x90, 0xf4, 0x80, 0x0a, 0x41, 0xa6, 0x34, 0xda, 0x06,
	0x2f, 0xa7, 0x42, 0x16, 0x8c, 0xc8, 0xa2, 0x66, 0x43, 0x67, 0xdb, 0x19, 0xbb, 0x69, 0xd3, 0x14,
	0x45, 0xd0, 0x61, 0xa4, 0xa2, 0xc3, 0xd6, 0xb6, 0x33, 0xee, 0xa7, 0x4a, 0x8e, 0xc6, 0xd0, 0x21,
	0x7c, 0x2a, 0x86, 0xed, 0x6d, 0x67, 0xec, 0xed, 0x5c, 0x4e, 0x74, 0xd5, 0xc4, 0x56, 0x4d, 0x76,
	0xd9, 0x32, 0x55, 0x1e, 0xf1, 0x1c, 0xfc, 0x83, 0x8c, 0x08, 0x69, 0xeb, 0xc5, 0xe0, 0x37, 0x92,
	0x0b, 0x55, 0xb0, 0x9f, 0xae, 0xd9, 0xfe, 0x63, 0xc5, 0xdf, 0x1c, 0x88, 0x9a, 0x2d, 0xa6, 0x54,
	0x2c, 0x4a, 0x19, 0x7d, 0x0c, 0x2e, 0xe5, 0xbc, 0xe6, 0xaa, 0xa2, 0xb7, 0x13, 0x24, 0x5f, 0x53,
	0x46, 0x79, 0x91, 0x3d, 0x42, 0xe3, 0xde, 0x46, 0xaa, 0xff, 0x46, 0x09, 0x6c, 0x72, 0x15, 0xa0,
	0xaa, 0xff, 0x43, 0xa5, 0xbd, 0x8d, 0xd4, 0x78, 0x45, 0xff, 0x87, 0x4d, 0x51, 0x2f, 0x78, 0x46,
	0x15, 0x32, 0x37, 0x35, 0xda, 0xfd, 0x00, 0x3c, 0xed, 0x31, 0x91, 0xcb, 0x39, 0x8d, 0xff, 0x72,
	0xc0, 0x6f, 0x16, 0x8c, 0x6e, 0x40, 0xe7, 0xb8, 0x60, 0xb9, 0x42, 0x33, 0xd8, 0xb9, 0xba, 0x86,
	0x26, 0x51, 0xdf, 0x27, 0x05, 0xcb, 0x53, 0xe5, 0x64, 0x36, 0x29, 0xe3, 0xc5, 0x5c, 0x6d, 0x92,
	0x5e, 0x97, 0xa6, 0x29, 0x4a, 0xa0, 0x9b, 0x53, 0x49, 0x8a, 0xf2, 0xfc, 0x15, 0xb2, 0x4e, 0x71,
	0x09, 0xfd, 0x55, 0x91, 0x28, 0x5c, 0xc7, 0x16, 0x6e, 0x44, 0x1e, 0x74, 0x0f, 0x8b, 0x8a, 0xd6,
	0x0b, 0x19, 0x3a, 0xd1, 0x16, 0x78, 0xdf, 0x31, 0x4e, 0x49, 0x36, 0x23, 0x2f, 0x4b, 0x1a, 0xb6,
	0xa2, 0x00, 0xfa, 0x0f, 0x08, 0xcb, 0x68, 0x59, 0xd2, 0x3c, 0x6c, 0x63, 0xf8, 0x33, 0xb2, 0x2c,
	0x6b, 0x92, 0xeb, 0xf0, 0x4e, 0x34, 0x00, 0xd8, 0x45, 0xbe, 0x6a, 0xdd, 0x8d, 0xff, 0x74, 0xc0,
	0x57, 0x06, 0xcb, 0x82, 0x4f, 0xd6, 0xba, 0xbf, 0x92, 0x34, 0x7f, 0x26, 0x07, 0x62, 0xda, 0xe8,
	0xfd, 0x2c, 0x32, 0x84, 0xd0, 0x96, 0x64, 0xaa, 0x3a, 0x6d, 0xa7, 0x28, 0x22, 0x3d, 0x72, 0x22,
	0xc9, 0xb0, 0x73, 0x1e, 0x3d, 0xd0, 0x23, 0xfe, 0x01, 0xba, 0xa6, 0x00, 0x76, 0x99, 0xd2, 0x9f,
	0x17, 0x54, 0xc8, 0x70, 0x23, 0xea, 0x83, 0x9b, 0xd2, 0x79, 0xb9, 0x0c, 0x1d, 0x14, 0x77, 0xc5,
	0x92, 0x65, 0x61, 0x2b, 0xba, 0x04, 0xc1, 0x73, 0xc9, 0x29, 0xa9, 0xac, 0x63, 0x1b, 0x97, 0xc3,
	0x9a, 0xd0, 0xbd, 0x83, 0xee, 0xb6, 0xd1, 0x5f, 0x1c, 0xf0, 0x1e, 0xbd, 0xa2, 0x99, 0xed, 0xf3,
	0x2a, 0x74, 0xe9, 0x2b, 0x9a, 0x4d, 0x0a, 0xdd, 0x6a, 0x3b, 0xdd, 0x44, 0x75, 0x3f, 0x8f, 0x46,
	0xd0, 0x3b, 0x2a, 0x4a, 0xda, 0xe8, 0x6c, 0xa5, 0x63, 0xc7, 0x86, 0xea, 0x6d, 0xec, 0x18, 0x65,
	0xec, 0x98, 0xb2, 0x93, 0x61, 0x47, 0x99, 0x50, 0xc4, 0x0c, 0x0b, 0x41, 0xb9, 0xca, 0xe0, 0xea,
	0x0c, 0x56, 0x8f, 0x7d, 0x00, 0x44, 0xa1, 0x99, 0x1f, 0x5f, 0x82, 0xad, 0x6f, 0x0a, 0x21, 0x1b,
	0xb8, 0xe2, 0x1f, 0xa1, 0x87, 0xea, 0x3e, 0x3b, 0xaa, 0xd7, 0xa0, 0x38, 0x6f, 0x41, 0x19, 0x41,
	0x8f, 0x48, 0x49, 0xb2, 0x19, 0xcd, 0x15, 0xcc, 0x5e, 0xba, 0xd2, 0xa3, 0x21, 0x74, 0xf9, 0x82,
	0xb1, 0x82, 0xe9, 0x8d, 0xe8, 0xa5, 0x56, 0x8d, 0x7f, 0x75, 0x60, 0x60, 0x2b, 0x9a, 0xe9, 0xbb,
	0x0d, 0x2e, 0x76, 0x8e, 0xf3, 0xde, 0x1e, 0x7b, 0x3b, 0xa3, 0x64, 0xfd, 0x7f, 0x82, 0xa2, 0x78,
	0xc4, 0x24, 0x5f, 0xa6, 0xda, 0x71, 0xf4, 0x40, 0xf7, 0xa0, 0x8d, 0xd8, 0xff, 0x31, 0x5d, 0x9a,
	0x45, 0x44, 0x31, 0xba, 0x06, 0xee, 0x09, 0x29, 0x17, 0xd4, 0xcc, 0x69, 0x3f, 0xb1, 0x0d, 0xa5,
	0xda, 0x7e, 0xb7, 0xf5, 0xa5, 0x13, 0x8f, 0x21, 0xd8, 0x55, 0x78, 0xcf, 0xd8, 0x90, 0x56, 0x73,
	0x43, 0xe2, 0x01, 0xf8, 0xda, 0xd3, 0x2c, 0xda, 0x5d, 0x08, 0x1e, 0xd2, 0xf7, 0x89, 0x7c, 0x97,
	0x8c, 0x98, 0x4b, 0xc7, 0x9a, 0x5c, 0xd7, 0xc1, 0x7b, 0x52, 0x94, 0xe5, 0x85, 0x18, 0x7c, 0x00,
	0xf4, 0x33, 0x51, 0x7f, 0x38, 0xd0, 0xdf, 0x7f, 0x6a, 0x83, 0xae, 0xaf, 0x4d, 0x4c, 0x94, 0xac,
	0xfe, 0xbc, 0x35, 0x2e, 0x48, 0x94, 0xfa, 0xc8, 0x6c, 0x16, 0x8a, 0x48, 0x27, 0x35, 0x1a, 0x08,
	0xd0, 0xd7, 0x43, 0xd0, 0x84, 0xd0, 0x59, 0x83, 0x70, 0xf3, 0xcd, 0x74, 0xf4, 0xc1, 0x15, 0x32,
	0x2f, 0x58, 0xb8, 0x11, 0x01, 0x6c, 0x0a, 0x99, 0xeb, 0xd3, 0x40, 0xcb, 0x94, 0xf3, 0xb0, 0x15,
	0x03, 0xf4, 0xf6, 0x9f, 0x1a, 0xb8, 0x1f, 0xe1, 0x7e, 0x15, 0xf2, 0xb9, 0x24, 0x72, 0x21, 0xd4,
	0xb1, 0xa8, 0x24, 0x73, 0xa3, 0x18, 0x2d, 0x0e, 0xc0, 0x3b, 0x9c, 0x91, 0x53, 0xcb, 0x43, 0x1f,
	0x00, 0x55, 0x93, 0x62, 0x0b, 0x82, 0xc7, 0x9c, 0xd2, 0xd7, 0xf6, 0xe4, 0xc6, 0x85, 0xd4, 0x06,
	0xe3, 0x30, 0x00, 0x7f, 0x8f, 0x96, 0x65, 0x6d, 0xff, 0xdf, 0x03, 0x4f, 0xe9, 0x86, 0x64, 0x97,
	0xc1, 0xa5, 0xf3, 0x3a, 0x9b, 0x19, 0x9a, 0x68, 0x05, 0x79, 0x7a, 0x42, 0xb9, 0xb0, 0x07, 0xa7,
	0x9b, 0x5a, 0x35, 0x7e, 0x01, 0xfe, 0xc1, 0x71, 0x5e, 0x70, 0xbb, 0xc6, 0x11, 0x74, 0xe6, 0x44,
	0xce, 0xcc, 0x14, 0x28, 0x19, 0x6d, 0x55, 0x9d, 0x6b, 0x96, 0x05, 0xa9, 0x92, 0xa3, 0x6b, 0xe0,
	0x55, 0xe4, 0x98, 0x4e, 0xe6, 0x84, 0x53, 0x26, 0x0d, 0xfb, 0x01, 0x4d, 0xcf, 0x94, 0x05, 0xbb,
	0x54, 0x89, 0xdf, 0x0c, 0xe0, 0x5e, 0x2d, 0x24, 0x4e, 0x94, 0x45, 0x7e, 0x13, 0x06, 0xd6, 0x64,
	0xc0, 0x8f, 0xa0, 0x37, 0x33, 0x16, 0x3b, 0x86, 0x56, 0x8f, 0x9f, 0x81, 0xff, 0x60, 0x56, 0xd5,
	0xf9, 0xbf, 0x05, 0x8a, 0x23, 0x4a, 0xb3, 0x05, 0x17, 0x74, 0x35, 0xa2, 0x5a, 0x45, 0x84, 0x2a,
	0xa3, 0x41, 0xf8, 0x13, 0x16, 0xa8, 0x4f, 0xd9, 0x79, 0x05, 0x42, 0x68, 0x2f, 0x0c, 0x65, 0x83,
	0x14, 0x45, 0xb4, 0x4c, 0x8b, 0x5c, 0xa5, 0x0e, 0x52, 0x14, 0x9b, 0x05, 0x3b, 0x67, 0x14, 0xac,
	0x4f, 0x99, 0x29, 0xf8, 0x19, 0x0c, 0x9e, 0x2f, 0xab, 0xb2, 0x60, 0xc7, 0xb6, 0x64, 0x08, 0x6d,
	0xc1, 0x33, 0x53, 0x11, 0x45, 0xb4, 0xe4, 0x42, 0x9a, 0xe3, 0x11, 0x45, 0x24, 0x88, 0x89, 0x32,
	0x69, 0xee, 0x41, 0x90, 0xd2, 0xaa, 0x3e, 0xa1, 0xe7, 0x01, 0x6f, 0x80, 0x6a, 0xad, 0x83, 0x1a,
	0x80, 0xaf, 0xc3, 0x4d, 0xba, 0x4f, 0xc1, 0x3b, 0x68, 0x24, 0x7b, 0x1f, 0x48, 0x3e, 0xc0, 0xc1,
	0x9b, 0x04, 0x5f, 0xc1, 0xd6, 0x21, 0x5f, 0xb0, 0x8c, 0x48, 0x7a, 0xc1, 0x5e, 0x89, 0xe2, 0x35,
	0x35, 0xe3, 0xaf, 0xe4, 0x38, 0x84, 0x81, 0x0d, 0x35, 0xc9, 0x3e, 0xc4, 0x8b, 0x86, 0xc8, 0x73,
	0x12, 0xc5, 0xbf, 0x3b, 0x00, 0xe8, 0x63, 0x38, 0x64, 0xef, 0x4a, 0xa7, 0x71, 0x57, 0x9e, 0x51,
	0x6b, 0xc5, 0x15, 0xfd, 0x64, 0xd1, 0x5c, 0xf9, 0x1c, 0x7a, 0x55, 0x9d, 0x4f, 0xf0, 0xbd, 0x68,
	0x6e, 0xd1, 0xd1, 0x3b, 0xb7, 0xe8, 0xa1, 0x7d, 0x4c, 0xa6, 0xdd, 0xaa, 0xce, 0x51, 0x8b, 0xae,
	0xc0, 0x66, 0x21, 0x26, 0x79, 0xc1, 0xd5, 0x25, 0xd4, 0x4b, 0xdd, 0x42, 0x3c, 0x2c, 0x78, 0x3c,
	0x83, 0xf0, 0x05, 0x2f, 0x24, 0x7d, 0x5c, 0x94, 0x17, 0xad, 0x84, 0x3a, 0x9c, 0x5a, 0x8d, 0xc3,
	0xe9, 0x32, 0xb8, 0x73, 0xca, 0x2b, 0xa1, 0x60, 0xb8, 0xa9, 0x56, 0xf0, 0x44, 0x21, 0xf3, 0x39,
	0x65, 0xb9, 0xa1, 0xb2, 0xd1, 0xe2, 0x1b, 0xb0, 0xb5, 0xaa, 0x64, 0x96, 0x61, 0x08, 0xdd, 0x53,
	0x5e, 0x48, 0x49, 0x99, 0x39, 0x09, 0xac, 0xba, 0xf3, 0x0a, 0xfa, 0xf3, 0xac, 0xce, 0xb2, 0x6f,
	0xb1, 0xe3, 0x3b, 0x10, 0x70, 0x7c, 0x27, 0x4e, 0xb2, 0xba, 0xaa, 0x08, 0xcb, 0xa3, 0x20, 0x69,
	0xbe, 0x1b, 0x47, 0xff, 0x4b, 0xce, 0x78, 0x46, 0x7e, 0x01, 0xbe, 0x0e, 0x12, 0xea, 0x0d, 0x10,
	0x05, 0x49, 0xf3, 0x79, 0x7b, 0x66, 0xcc, 0xd8, 0xb9, 0xed, 0xdc, 0x0f, 0xbf, 0x1f, 0xa8, 0x27,
	0xfc, 0x44, 0x2d, 0x66, 0x56, 0x97, 0x2f, 0x37, 0x95, 0x74, 0xe7, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x69, 0xe5, 0xda, 0x59, 0xdb, 0x0b, 0x00, 0x00,
}
