# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import agent_pb2 as agent__pb2


class pcoccNodeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.route_command = channel.unary_unary(
        '/pcoccNode/route_command',
        request_serializer=agent__pb2.RouteMessage.SerializeToString,
        response_deserializer=agent__pb2.RouteMessageResult.FromString,
        )
    self.route_stream = channel.stream_stream(
        '/pcoccNode/route_stream',
        request_serializer=agent__pb2.McastMessage.SerializeToString,
        response_deserializer=agent__pb2.RouteMessageResult.FromString,
        )


class pcoccNodeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def route_command(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def route_stream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_pcoccNodeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'route_command': grpc.unary_unary_rpc_method_handler(
          servicer.route_command,
          request_deserializer=agent__pb2.RouteMessage.FromString,
          response_serializer=agent__pb2.RouteMessageResult.SerializeToString,
      ),
      'route_stream': grpc.stream_stream_rpc_method_handler(
          servicer.route_stream,
          request_deserializer=agent__pb2.McastMessage.FromString,
          response_serializer=agent__pb2.RouteMessageResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pcoccNode', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
